ticket_panel:
    title: "Ouvrir Un Ticket"
    description: "Merci d’ouvrir un ticket que si la présence du support est obligatoire. Sinon, merci de vous rendre dans le <#1019662752651952219>"
    color: "#303030"
    footer: "Eternodes | Bot made by 0xyToan"
    buttons:
        open_ticket: "Ouvrir un ticket"
        open_ticket_style: "PRIMARY" # Don't modify this if you don't known what you are doing
    confirmation: "Le ticket à bien été ouvert!"

in_tickets:
    title: "Ticket"
    description: "move dans index.js"
    color: "#303030"
    footer: "Eternodes | Bot made by 0xyToan"
    buttons:
        close_ticket: "Close the ticket"
        close_ticket_style: "DANGER" # Don't modify this if you don't known what you are doing

support_control:
    title: "Ticket"
    description: "Support team control:"
    color: "#303030"
    buttons:
        del_ticket: "Delete the ticket"
        del_ticket_style: "DANGER" # Don't modify this if you don't known what you are doing
        save_trans: "Save the transcript"
        save_trans_style: "SUCCESS" # Don't modify this if you don't known what you are doing
